export const USER_POSITION = {
  result: 'success',
  list: [
    {
      positionName: '테스트',
      positionId: '96461E59352E4A9E',
      isChecked: false,
      title: '테스트',
    },
    {
      positionName: '사원',
      positionId: 'F865B344331209AF',
      isChecked: false,
      title: '사원',
    },
    {
      positionName: '차장',
      positionId: 'D2BED602E177062E',
      isChecked: false,
      title: '차장',
    },
    {
      positionName: '주임',
      positionId: '7D1A20C42C0507B8',
      isChecked: false,
      title: '주입',
    },
    {
      positionName: '대리',
      positionId: 'B618C4A347B78B83',
      isChecked: false,
      title: '대리',
    },
  ],
};

export const USER_GRADE = {
  result: '20000',
  list: [
    {
      userGradeId: '208E561E09C22A3F',
      userGradeIdx: 1,
      userGradeName: '다이아',
      userGradeIcon: 'IcGrade0',
      isChecked: false,
      title: '다이아',
    },
    {
      userGradeId: '50EF55A9B388D629',
      userGradeIdx: 2,
      userGradeName: '킹',
      userGradeIcon: 'IcGrade1',
      isChecked: false,
      title: '킹',
    },
  ],
};

export const ADMIN_GROUP = {
  result: '20000',
  selectList: [
    {
      groupId: '1D9DA48B9870E5BB',
      groupName: 'eden company',
      parentGroupId: '1D9DA48B9870E5BB',
      groupDepth: '1D9DA48B9870E5BB',
      groupDepthLevel: 1,
      groupFullName: 'eden company',
      groupUserCnt: 2,
      groupStaffCnt: 1,
      groupLeaderCnt: 1,
      groupLeaderAprvCnt: 1,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 1,
      leaderAprvCnt: 1,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden company',
    },
    {
      groupId: 'BC63010A9F852818',
      groupName: 'eden story',
      parentGroupId: '1D9DA48B9870E5BB',
      groupDepth: '1D9DA48B9870E5BB/BC63010A9F852818',
      groupDepthLevel: 2,
      groupFullName: 'eden company/eden story',
      groupUserCnt: 1,
      groupStaffCnt: 1,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden story',
    },
    {
      groupId: '12AC1B666DF10A22',
      groupName: 'eden task',
      parentGroupId: 'BC63010A9F852818',
      groupDepth: '1D9DA48B9870E5BB/BC63010A9F852818/12AC1B666DF10A22',
      groupDepthLevel: 3,
      groupFullName: 'eden company/eden story/eden task',
      groupUserCnt: 0,
      groupStaffCnt: 0,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden task',
    },
    {
      groupId: '5E46573BC5CC62C6',
      groupName: 'eden task2',
      parentGroupId: 'BC63010A9F852818',
      groupDepth: '1D9DA48B9870E5BB/BC63010A9F852818/5E46573BC5CC62C6',
      groupDepthLevel: 3,
      groupFullName: 'eden company/eden story/eden task2',
      groupUserCnt: 0,
      groupStaffCnt: 0,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden task2',
    },
    {
      groupId: '1D9DA48B9870E5BC',
      groupName: 'eden company',
      parentGroupId: '1D9DA48B9870E5BC',
      groupDepth: '1D9DA48B9870E5BC',
      groupDepthLevel: 1,
      groupFullName: 'eden company2',
      groupUserCnt: 2,
      groupStaffCnt: 1,
      groupLeaderCnt: 1,
      groupLeaderAprvCnt: 1,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 1,
      leaderAprvCnt: 1,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden company',
    },
    {
      groupId: 'BC63010A9F85281C',
      groupName: 'eden story2',
      parentGroupId: '1D9DA48B9870E5BC',
      groupDepth: '1D9DA48B9870E5BC/BC63010A9F85281C',
      groupDepthLevel: 2,
      groupFullName: 'eden company2/eden story2',
      groupUserCnt: 1,
      groupStaffCnt: 1,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden story',
    },
    {
      groupId: '12AC1B666DF10A2C',
      groupName: 'eden task2',
      parentGroupId: 'BC63010A9F85281C',
      groupDepth: '1D9DA48B9870E5BC/BC63010A9F85281C/12AC1B666DF10A2C',
      groupDepthLevel: 3,
      groupFullName: 'eden company2/eden story2/eden task2',
      groupUserCnt: 0,
      groupStaffCnt: 0,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden task',
    },
    {
      groupId: '5E46573BC5CC62CC',
      groupName: 'eden task3',
      parentGroupId: 'BC63010A9F85281C',
      groupDepth: '1D9DA48B9870E5BC/BC63010A9F85281C/5E46573BC5CC62CC',
      groupDepthLevel: 3,
      groupFullName: 'eden company/eden story/eden task2',
      groupUserCnt: 0,
      groupStaffCnt: 0,
      groupLeaderCnt: 0,
      groupLeaderAprvCnt: 0,
      groupLeaderNoAprvCnt: 0,
      leaderCnt: 0,
      leaderAprvCnt: 0,
      leaderNoAprvCnt: 0,
      isLeader: '1',
      isPermitApproval: '1',
      isChecked: false,
      title: 'eden task3',
    },
  ],
};
